/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;
import backEnd.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Rifaul06
 */
public class FormStudio extends javax.swing.JFrame {
    
    /**
     * Creates new form FormStudio
     */
    public FormStudio() {
        initComponents();
        showData();
        setCmbFilm();
        emptyForm();
    }
    public void emptyForm(){
        txtIdStudio.setText("0");
        cmbJudulFilm.setSelectedIndex(0);
        txtStudio.setText("");
    }
    public void showData(){
        String[] kolom = {"ID","Studio","Film"};
        ArrayList<Studio> list = new Studio().getAll();
        Object row[] = new Object[3];
        tblStudio.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for (int i = 0; i < list.size(); i++) {
            row[0]= list.get(i).getIdStudio();
            row[1]= list.get(i).getStudio();
            row[2]= list.get(i).getFilm().getJudul();
            ((DefaultTableModel)tblStudio.getModel()).addRow(row);
        }        
    }
    public void setCmbFilm(){
        cmbJudulFilm.setModel(new DefaultComboBoxModel(new Film().getAll().toArray()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudio = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdStudio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbJudulFilm = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        mnKasir = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        mnFilm = new javax.swing.JMenuItem();
        mnStudio = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pengaturan Studio");

        tblStudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudio);

        jLabel2.setText("id Studio");

        txtIdStudio.setEditable(false);

        jLabel3.setText("nama Studio");

        jLabel4.setText("Judul Film");

        cmbJudulFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        FileMenu.add(mnKasir);

        mnKeluar.setText("Keluar");
        FileMenu.add(mnKeluar);

        jMenuBar1.add(FileMenu);

        Edit.setText("Edit");

        mnFilm.setText("Film");
        mnFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFilmActionPerformed(evt);
            }
        });
        Edit.add(mnFilm);

        mnStudio.setText("Studio");
        mnStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudioActionPerformed(evt);
            }
        });
        Edit.add(mnStudio);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        Edit.add(mnTransaksi);

        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudio)
                                    .addComponent(cmbJudulFilm, 0, 219, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJudulFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Studio s = new Studio();
        s.setIdStudio(Integer.parseInt(txtIdStudio.getText()));
        s.setFilm((Film)cmbJudulFilm.getSelectedItem());
        s.setStudio(txtStudio.getText());
        s.save();
        txtIdStudio.setText(Integer.toString(s.getIdStudio()));
        showData();
        Pembelian p = new Pembelian();
        p.setIdPembelian(0);
        p.setStudio(s);
        p.getKursi().setKode("A0");
        p.getKursi().setStatus("book");
        p.save();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblStudio.getModel();
        int row = tblStudio.getSelectedRow();
        Studio s = new Studio().getByidStudio(Integer.parseInt(model.getValueAt(row, 0).toString()));
        s.delete();
        emptyForm();
        showData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        emptyForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblStudio.getModel();
        int row = tblStudio.getSelectedRow();
        Studio s = new Studio().getByidStudio(Integer.parseInt(model.getValueAt(row, 0).toString()));
        
        txtIdStudio.setText(String.valueOf(s.getIdStudio()));
        cmbJudulFilm.getModel().setSelectedItem(s.getFilm());
        txtStudio.setText(s.getStudio());
    }//GEN-LAST:event_tblStudioMouseClicked

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        // TODO add your handling code here:
        FormPembelian frmBeli = new FormPembelian();
        frmBeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void mnFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFilmActionPerformed
        // TODO add your handling code here:
        FrmFilm frmFilm = new FrmFilm();
        frmFilm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFilmActionPerformed

    private void mnStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudioActionPerformed
        // TODO add your handling code here:
        FormStudio frmStudio = new FormStudio();
        frmStudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnStudioActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbJudulFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnFilm;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnStudio;
    private javax.swing.JMenuItem mnTransaksi;
    private javax.swing.JTable tblStudio;
    private javax.swing.JTextField txtIdStudio;
    private javax.swing.JTextField txtStudio;
    // End of variables declaration//GEN-END:variables
}
