/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;
import backEnd.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author soyidwahyud
 */
public class FormTransaksi extends javax.swing.JFrame {
    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        showData();
    }
    
    public void emptyForm()
    {
        txtIdStudio.setText("0");
        txtStudio.setText("");
    }
    
    public void showData()
    {
        String[] kolom = {"ID","Studio","Film","kursi","Total harga"};
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object row[] = new Object[5];
        tblTransaksi.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for (int i = 0; i < list.size(); i++) {
            row[0]= list.get(i).getIdTransaksi();
            row[1]= list.get(i).getStudio();
            row[2]= list.get(i).getJudul();
            row[3]= list.get(i).getKodekursi();
            row[4]= list.get(i).getTotal();
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(row);
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        mnKasir = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        mnFilm = new javax.swing.JMenuItem();
        mnStudio = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        txtIdStudio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbJudulFilm = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnBayar = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        FileMenu1 = new javax.swing.JMenu();
        mnKasir1 = new javax.swing.JMenuItem();
        mnKeluar1 = new javax.swing.JMenuItem();
        Edit1 = new javax.swing.JMenu();
        mnFilm1 = new javax.swing.JMenuItem();
        mnStudio1 = new javax.swing.JMenuItem();

        FileMenu.setText("File");

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        FileMenu.add(mnKasir);

        mnKeluar.setText("Keluar");
        FileMenu.add(mnKeluar);

        jMenuBar1.add(FileMenu);

        Edit.setText("Edit");

        mnFilm.setText("Film");
        mnFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFilmActionPerformed(evt);
            }
        });
        Edit.add(mnFilm);

        mnStudio.setText("Studio");
        mnStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudioActionPerformed(evt);
            }
        });
        Edit.add(mnStudio);

        jMenuBar1.add(Edit);

        jLabel2.setText("id Studio");

        txtIdStudio.setEditable(false);

        jLabel3.setText("nama Studio");

        jLabel4.setText("Judul Film");

        cmbJudulFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Simpan");

        btnDelete.setText("Hapus");

        btnAdd.setText("Tambah");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transaksi");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnBaru.setText("Delete");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        FileMenu1.setText("File");

        mnKasir1.setText("Kasir");
        mnKasir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasir1ActionPerformed(evt);
            }
        });
        FileMenu1.add(mnKasir1);

        mnKeluar1.setText("Keluar");
        FileMenu1.add(mnKeluar1);

        jMenuBar2.add(FileMenu1);

        Edit1.setText("Edit");

        mnFilm1.setText("Film");
        mnFilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFilm1ActionPerformed(evt);
            }
        });
        Edit1.add(mnFilm1);

        mnStudio1.setText("Studio");
        mnStudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudio1ActionPerformed(evt);
            }
        });
        Edit1.add(mnStudio1);

        jMenuBar2.add(Edit1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBaru)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(btnBaru))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        Studio s = new Studio().getByidStudio(Integer.parseInt(model.getValueAt(row, 0).toString()));

        txtIdStudio.setText(String.valueOf(s.getIdStudio()));
        cmbJudulFilm.getModel().setSelectedItem(s.getFilm());
        txtStudio.setText(s.getStudio());
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        // TODO add your handling code here:
        FormPembelian frmBeli = new FormPembelian();
        frmBeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void mnFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFilmActionPerformed
        // TODO add your handling code here:
        FrmFilm frmFilm = new FrmFilm();
        frmFilm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFilmActionPerformed

    private void mnStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudioActionPerformed
        // TODO add your handling code here:
        FormStudio frmStudio = new FormStudio();
        frmStudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnStudioActionPerformed

    private void mnKasir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasir1ActionPerformed
        // TODO add your handling code here:
        FormPembelian frmBeli = new FormPembelian();
        frmBeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKasir1ActionPerformed

    private void mnFilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFilm1ActionPerformed
        // TODO add your handling code here:
        FrmFilm frmFilm = new FrmFilm();
        frmFilm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFilm1ActionPerformed

    private void mnStudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudio1ActionPerformed
        // TODO add your handling code here:
        FormStudio frmStudio = new FormStudio();
        frmStudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnStudio1ActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        Studio s = new Studio();
        s.setIdStudio(Integer.parseInt(txtIdStudio.getText()));
        s.setFilm((Film)cmbJudulFilm.getSelectedItem());
        s.setStudio(txtStudio.getText());
        s.save();
        txtIdStudio.setText(Integer.toString(s.getIdStudio()));
        showData();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        emptyForm();
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        Transaksi transaksi = new Transaksi().getByIdTransaksi(Integer.parseInt(model.getValueAt(row, 0).toString()));
        transaksi.delete();
        emptyForm();
        showData();
    }//GEN-LAST:event_btnBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu Edit1;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu FileMenu1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbJudulFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnFilm;
    private javax.swing.JMenuItem mnFilm1;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenuItem mnKasir1;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnKeluar1;
    private javax.swing.JMenuItem mnStudio;
    private javax.swing.JMenuItem mnStudio1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtIdStudio;
    private javax.swing.JTextField txtStudio;
    // End of variables declaration//GEN-END:variables
}
