/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;
import backEnd.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rifaul06
 */
public class FrmFilm extends javax.swing.JFrame {

    /**
     * Creates new form FrmFilm
     */
    public FrmFilm() {
        initComponents();       
        kosongkanForm();
        tampilData();
    }
    public void kosongkanForm(){
        txtidFilm.setText("0");
        TxtJudul.setText("");
        //txtGenre.setText("");
    }
    public void tampilData(){
        String[] kolom = {"Id","Judul"};
        ArrayList<Film> list = new Film().getAll();
        Object rowData[] = new Object[2];
        tableFilm.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for (Film film : list) {
            rowData[0] = film.getIdFilm();
            rowData[1] = film.getJudul();
            //rowData[2] = film.getGenre();
            ((DefaultTableModel)tableFilm.getModel()).addRow(rowData);
        }
    }
    public void cari(String keyword){
        String[] kolom = {"id", "judul"};
        ArrayList<Film> list = new Film().search(keyword);
        Object rowData[] = new Object[2];
        tableFilm.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        for (Film film : list) {
            rowData[0] = film.getIdFilm();
            rowData[1] = film.getJudul();
            //rowData[2] = film.getGenre();
            ((DefaultTableModel)tableFilm.getModel()).addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnAddFilm = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        TxtJudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFilm = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidFilm = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        mnKasir = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        mnFilm = new javax.swing.JMenuItem();
        mnStudio = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddFilm.setText("Add");
        btnAddFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilmActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        TxtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJudulActionPerformed(evt);
            }
        });

        jLabel3.setText("Judul Film");

        tableFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFilmMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableFilm);

        jLabel1.setText("Pengaturan Film");

        jLabel2.setText("id Film");

        txtidFilm.setEditable(false);

        FileMenu.setText("File");

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        FileMenu.add(mnKasir);

        mnKeluar.setText("Keluar");
        FileMenu.add(mnKeluar);

        jMenuBar1.add(FileMenu);

        Edit.setText("Edit");

        mnFilm.setText("Film");
        mnFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFilmActionPerformed(evt);
            }
        });
        Edit.add(mnFilm);

        mnStudio.setText("Studio");
        mnStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudioActionPerformed(evt);
            }
        });
        Edit.add(mnStudio);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        Edit.add(mnTransaksi);

        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAddFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFilm)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(btnSave)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJudulActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Film film = new Film();
        film.setIdFilm(Integer.parseInt(txtidFilm.getText()));
        film.setJudul(TxtJudul.getText());
        //film.setGenre(txtGenre.getText());
        film.save();
        txtidFilm.setText(Integer.toString(film.getIdFilm()));
        tampilData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilmActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnAddFilmActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableFilm.getModel();
        int row = tableFilm.getSelectedRow();
        Film film = new Film().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        film.delete();
        kosongkanForm();
        tampilData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        // TODO add your handling code here:
        FormPembelian frmBeli = new FormPembelian();
        frmBeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void mnFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFilmActionPerformed
        // TODO add your handling code here:
        FrmFilm frmFilm = new FrmFilm();
        frmFilm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFilmActionPerformed

    private void mnStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudioActionPerformed
        // TODO add your handling code here:
        FormStudio frmStudio = new FormStudio();
        frmStudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnStudioActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void tableFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFilmMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableFilm.getModel();
        int row = tableFilm.getSelectedRow();
        Film film = new Film();
        film = film.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        txtidFilm.setText(String.valueOf(film.getIdFilm()));
        TxtJudul.setText(film.getJudul());
        //txtGenre.setText(film.getGenre());
        
    }//GEN-LAST:event_tableFilmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JTextField TxtJudul;
    private javax.swing.JButton btnAddFilm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnFilm;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnStudio;
    private javax.swing.JMenuItem mnTransaksi;
    private javax.swing.JTable tableFilm;
    private javax.swing.JTextField txtidFilm;
    // End of variables declaration//GEN-END:variables
}
