/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;
import backEnd.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author soyidwahyud
 */
public class FrmMakanan extends javax.swing.JFrame {

    /**
     * Creates new form FrmMakanan
     */
    public boolean click = false;
    public FrmMakanan() {
        initComponents();
        kosongkanForm();
        tampilData();
    }
    public void kosongkanForm(){
        jTextMakan.setText("0");
        jTextnamaMakan.setText("");
        jTextHarga.setText("");
        click = false;
    }
    public void tampilData(){
        String[] kolom = {"idmakanan","nama_makanan","harga"};
        ArrayList<Makanan> list = new Makanan().getAll();
        Object rowData[] = new Object[3];
        TableMakanan.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for (Makanan makanan : list) {
            rowData[0] = makanan.getIdmakanan();
            rowData[1] = makanan.getNama_makanan();
            rowData[2] = makanan.getHarga();
            ((DefaultTableModel)TableMakanan.getModel()).addRow(rowData);
        }
    }
    public void cari(String keyword){
        String[] kolom = {"idmakanan", "nama_makanan","harga"};
        ArrayList<Makanan> list = new Makanan().search(keyword);
        Object rowData[] = new Object[3];
        TableMakanan.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        for (Makanan makanan : list) {
            rowData[0] = makanan.getIdmakanan();
            rowData[1] = makanan.getNama_makanan();
            rowData[2] = makanan.getHarga();
            ((DefaultTableModel)TableMakanan.getModel()).addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Makanan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMakanan = new javax.swing.JTable();
        LabelMakanan = new javax.swing.JLabel();
        jTextMakan = new javax.swing.JTextField();
        JlabelNamamakan = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jTextnamaMakan = new javax.swing.JTextField();
        jTextHarga = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        mnKasir = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        mnFilm = new javax.swing.JMenuItem();
        mnStudio = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Makanan.setText("Pengaturan Makanan");

        TableMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableMakanan);

        LabelMakanan.setText("Id Makanan");

        jTextMakan.setEnabled(false);
        jTextMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMakanActionPerformed(evt);
            }
        });

        JlabelNamamakan.setText("Nama Makanan");

        jLabelHarga.setText("Harga");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        FileMenu.add(mnKasir);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        FileMenu.add(mnKeluar);

        jMenuBar1.add(FileMenu);

        Edit.setText("Edit");

        mnFilm.setText("Film");
        mnFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFilmActionPerformed(evt);
            }
        });
        Edit.add(mnFilm);

        mnStudio.setText("Studio");
        mnStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudioActionPerformed(evt);
            }
        });
        Edit.add(mnStudio);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        Edit.add(mnTransaksi);

        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Makanan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelMakanan)
                                .addGap(29, 29, 29)
                                .addComponent(jTextMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlabelNamamakan)
                                    .addComponent(jLabelHarga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextnamaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Makanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMakanan)
                    .addComponent(jTextMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelNamamakan)
                    .addComponent(jTextnamaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHarga)
                    .addComponent(jTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jDelete)
                    .addComponent(jSave))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        // TODO add your handling code here:
        FormPembelian frmBeli = new FormPembelian();
        frmBeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFilmActionPerformed
        // TODO add your handling code here:
        FrmFilm frmFilm = new FrmFilm();
        frmFilm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFilmActionPerformed

    private void mnStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudioActionPerformed
        // TODO add your handling code here:
        FormStudio frmStudio = new FormStudio();
        frmStudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnStudioActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void jTextMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMakanActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        Makanan m = new Makanan();
        m.setIdmakanan(Integer.parseInt(jTextMakan.getText()));
        m.setNama_makanan(jTextnamaMakan.getText());
        m.setHarga(Integer.parseInt(jTextHarga.getText().toString()));
        m.save();
        jTextMakan.setText(Integer.toString(m.getIdmakanan()));
        tampilData();
    }//GEN-LAST:event_jSaveActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TableMakanan.getModel();
        int row = TableMakanan.getSelectedRow();
        Makanan m = new Makanan().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        m.delete();
        kosongkanForm();
        tampilData();
    }//GEN-LAST:event_jDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel JlabelNamamakan;
    private javax.swing.JLabel LabelMakanan;
    private javax.swing.JLabel Makanan;
    private javax.swing.JTable TableMakanan;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextHarga;
    private javax.swing.JTextField jTextMakan;
    private javax.swing.JTextField jTextnamaMakan;
    private javax.swing.JMenuItem mnFilm;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnStudio;
    private javax.swing.JMenuItem mnTransaksi;
    // End of variables declaration//GEN-END:variables
}
